#!/bin/bash
echo 'file.c name?'
read file

echo 'prototype?'
read prototype

echo 'function description?'
read function_description

tuhermana="/*\n * File: $file\n * Auth: Gabriel Morffe\n */\n\n#include \"main.h\"\n\n/**\n * $prototype - $function_description\n *\n * Return: Always 0 (Success)\n */\n$prototype\n{\n/*yourcodebitch*/\n	return (0);\n}"

echo -e "$tuhermana" > "$file"

